[package]
name = "ssbfile"
version = "0.1.0"
authors = ["tehz"]

[dependencies]
ssb-resource = { path = "ssb-resource" } 
clap = "2.29.0"
failure = "0.1.1"
path_abs = "0.3.8"
log = "0.4.1"
simplelog = "0.5.1"

[workspace]